SELECT * from (
--总体
SELECT T1.MATERIAL as PVA站批号,
to_char(TO_DATE(ts.TRANSACTIONTIME,'yyyy/mm/dd hh24:mi:ss'),'yyyy/mm/dd') as PSA站生产时间,
T3.sublot as PSA站合并批,
to_char(TO_DATE(T4.TRANSACTIONTIME,'yyyy/mm/dd hh24:mi:ss'),'yyyy/mm/dd') as PVA站生产时间,
T5.SPILIT_LOT as 分条批号,
T1.LOT as 后段批号,
T6.sublot as 检查合并批,
T2.CUST_DEVICE as 客户批号,
to_char(TO_DATE(T7.TRANSACTIONTIME,'yyyy/mm/dd hh24:mi:ss'),'yyyy/mm/dd') as 检查站CheckOutDate,
T2.DEVICE as 成品料号,
T2.WO as 后段工单,
T8.WO as 前段工单,
T9.ARRANGE_QUANTITY as 成品批量,
T10.QUANTITY as A规,
/*点缺明细*/
T11.REASON,
T11.DESCR,
T11.QUANTITY,
t12.lot as 半成品料号
FROM (
select MATERIAL,LOT from MES.MES_WIP_LOT_NONACTIVE TT WHERE
 MATERIAL NOT LIKE 'KP1-S%'
UNION ALL
SELECT * FROM
(select DISTINCT TT.MATERIAL,B.LOT from MES.MES_WIP_LOT_NONACTIVE TT RIGHT JOIN
(select MATERIAL,LOT from MES.MES_WIP_LOT_NONACTIVE where
 material like 'KP1-S%') b  ON B.MATERIAL=TT.LOT
 WHERE 1=1

 )T) T1 LEFT JOIN
 MES.MES_WIP_LOT_NONACTIVE T2 ON T1.LOT=T2.LOT
 /*PVA站合并批*/
 LEFT JOIN (select b.sublot,PARENTLOT from  MES.MES_WIP_MERGE b
where b.operation='PSA' )T3 ON T2.MATERIAL=T3.PARENTLOT
/*PVA站生产时间*/
LEFT JOIN (select TRANSACTIONTIME,lot from MES.MES_WIP_HIST where  OPERATIONNO='PVA' AND TRANSACTION='CheckOut'
)T4
on T1.MATERIAL=T4.LOT
LEFT JOIN (select TRANSACTIONTIME,lot from MES.MES_WIP_HIST where  OPERATIONNO='PSA' AND TRANSACTION='CheckOut'
)ts
on T1.MATERIAL=ts.LOT

/*分条批号*/
LEFT JOIN (select MATERIAL AS SPILIT_LOT,lot  from mes.MES_WIP_LOT_NONACTIVE where MATERIAL LIKE 'KP1-S%')T5 ON
T1.LOT=T5.LOT
/*检查合并批*/
LEFT JOIN (select b.sublot,PARENTLOT from  MES.MES_WIP_MERGE b
where b.OPERATION = '檢查_1')T6 ON T1.MATERIAL=T6.PARENTLOT
/*检查站CheckOutDate*/
LEFT JOIN (select TRANSACTIONTIME,WIP_HIST_SID,LOT from mes.MES_WIP_HIST where TRANSACTION='Terminated')T7 ON T1.LOT=T7.LOT
/*前段工单*/
LEFT JOIN(select WO,LOT from MES.MES_WIP_LOT_NONACTIVE)T8 ON T1.MATERIAL=T8.LOT
/*成品批量*/
LEFT JOIN(select SUM(NVL(ARRANGE_QUANTITY,0))-SUM(NVL(QUANTITY,0))AS ARRANGE_QUANTITY,lot from mes.CMMT_BACK_INSPECT a
left join (select CMMT_BACKEND_INSPECT_SID,SUM(NVL(QUANTITY,0))QUANTITY FROM mes.CMMT_BACK_INSPECT_BIN
WHERE BIN IN ('R1','R2','R3','R4','R9')
GROUP BY CMMT_BACKEND_INSPECT_SID)
b on a.CMMT_BACKEND_INSPECT_SID=b.CMMT_BACKEND_INSPECT_SID
GROUP BY lot)T9 ON T1.LOT =T9.LOT
/*A规*/
LEFT JOIN (select SUM(NVL(b.QUANTITY,0)) AS QUANTITY,a.CMMT_BACKEND_INSPECT_SID,a.lot
from mes.CMMT_BACK_INSPECT a left join mes.CMMT_BACK_INSPECT_BIN b on a.CMMT_BACKEND_INSPECT_SID=b.CMMT_BACKEND_INSPECT_SID
where BIN IN ('A','A1','A2','A3','A4','A5','A6','Q1','R9','R10','R11','R12','R13','R14','R15','R16','R17','R18')
GROUP BY a.CMMT_BACKEND_INSPECT_SID,a.lot
 ) T10 ON T1.LOT=T10.LOT
 /*点缺明细*/
 LEFT JOIN (select REASON, DESCR, QUANTITY,CMMT_BACKEND_INSPECT_SID from mes.CMMT_BACK_INSPECT_DEFECT)T11
 ON T10.CMMT_BACKEND_INSPECT_SID=T11.CMMT_BACKEND_INSPECT_SID
 left join (select MATERIAL,LOT from mes.MES_WIP_LOT_NONACTIVE where MATERIAL  not  like 'KP1-S%')T12
 on t1.lot=t12.lot
 WHERE 1=1
 AND (T9.ARRANGE_QUANTITY<>'' OR T9.ARRANGE_QUANTITY IS NOT NULL)
 order BY T11.QUANTITY DESC
)a
where DESCR  is  not null
order by QUANTITY  desc