SELECT LIST_NO FROM WMS.A_TRANSACTION_HIST
WHERE ITEM_CODE like '%料号（ITEM_CODE）%'
        AND SUBINVENTORY_CODE like '%仓别（SUBINVENTORY_CODE）%'
        AND PALLET_NO like '%标签id（PALLET_NO）%'
		AND TRANSACTION_TYPE != 'ERP'