SELECT USER_NAME FROM WMS.A_USER WHERE USER_NO in
(SELECT distinct MODIFY_USER_NO FROM WMS.V_INVENTORY
WHERE ITEM_CODE like '%料号（ITEM_CODE）%'
        AND SUBINVENTORY_CODE like '%仓别（SUBINVENTORY_CODE）%'
        AND PALLET_NO like '%标签id（PALLET_NO）%')