SELECT DISTINCT A.ITEM_CODE, A.ONHAND_QUANTITY, B.UNIT_LENGTH, B.UNIT_WIDTH
FROM APPS.YWMS_ONHAND_QUANTITY A
 INNER JOIN APPS.MTL_SYSTEM_ITEMS B
 ON A.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID
 WHERE A.CATEGORY_SEG1 = '成品'
 AND A.SUBINVENTORY_CODE = 'F1FGA'