SELECT DISTINCT SEGMENT1,COMPONENT_QUANTITY FROM
(SELECT DISTINCT BB.SEGMENT1,AA.COMPONENT_QUANTITY,AA.LAST_UPDATE_DATE FROM 
	(	SELECT DISTINCT A.COMPONENT_ITEM_ID, A.COMPONENT_QUANTITY,A.LAST_UPDATE_DATE	
		FROM apps.BOM_INVENTORY_COMPONENTS_V A
			INNER JOIN APPS.BOM_BILL_OF_MATERIALS_V B
			ON A.BILL_SEQUENCE_ID = B.BILL_SEQUENCE_ID
	) AA
	left JOIN 
	( SELECT SEGMENT1, INVENTORY_ITEM_ID	
		FROM apps.MTL_SYSTEM_ITEMS
	) BB
	ON AA.COMPONENT_ITEM_ID = BB.INVENTORY_ITEM_ID
	) C
	WHERE SEGMENT1 = 'thisno'
	and LAST_UPDATE_DATE = (
		SELECT max(LAST_UPDATE_DATE) FROM
			(SELECT DISTINCT BB.SEGMENT1,AA.COMPONENT_QUANTITY,AA.LAST_UPDATE_DATE FROM 
				(	SELECT DISTINCT A.COMPONENT_ITEM_ID, A.COMPONENT_QUANTITY,A.LAST_UPDATE_DATE	
					FROM apps.BOM_INVENTORY_COMPONENTS_V A
						INNER JOIN APPS.BOM_BILL_OF_MATERIALS_V B
						ON A.BILL_SEQUENCE_ID = B.BILL_SEQUENCE_ID
				) AA
				left JOIN 
				( SELECT SEGMENT1, INVENTORY_ITEM_ID	
					FROM apps.MTL_SYSTEM_ITEMS
				) BB
				ON AA.COMPONENT_ITEM_ID = BB.INVENTORY_ITEM_ID
				) C
				WHERE SEGMENT1 = 'thisno'
				group by SEGMENT1
	)