select A.ASSET_ID 资产编号,C.DESCRIPTION 资产名称
			,E.SEGMENT1 || E.SEGMENT2 || E.SEGMENT3 || E.SEGMENT4 存放地点
			,SUBSTR(TO_CHAR(A.DEPRN_START_DATE,'YYYY-mm-dd'),0,10) 资本化时间
			,A.LIFE_IN_MONTHS 使用期,A.COST 本币原值
			,round(A.COST/A.LIFE_IN_MONTHS,2) 每月折旧额
			,round(A.COST/A.LIFE_IN_MONTHS*abs(ceil(months_between(A.DEPRN_START_DATE,TRUNC(SYSDATE)))),2) 累计折旧
			,B.ATTRIBUTE_CATEGORY_CODE 资产属性
			,D.ASSET_ID
			,E.LOCATION_ID


from apps.FA_BOOKS A
			,APPS.FA_ADDITIONS_B B
			,APPS.FA_ADDITIONS_TL C
			,APPS.FA_DISTRIBUTION_HISTORY D
			,APPS.FA_LOCATIONS E
WHERE A.DATE_INEFFECTIVE IS NULL
			AND B.ASSET_ID = A.ASSET_ID
			AND A.ASSET_ID = C.ASSET_ID
			AND A.ASSET_ID = D.ASSET_ID
			AND D.LOCATION_ID = E.LOCATION_ID
			AND A.COST <> 0
			AND B.ATTRIBUTE_CATEGORY_CODE NOT LIKE '土地%'
			AND B.ATTRIBUTE_CATEGORY_CODE NOT LIKE '遞延%'
ORDER BY A.ASSET_ID
