SELECT
 n.TRIP_NO,
 to_char(l.SCHEDULE_SHIP_DATE, 'yyyy-mm-dd') as SHIPMENT_DATE,
 n.DELIVERY_NO,
 l.SHIPPING_QUANTITY,
 l.ORDER_QUANTITY_UOM,
 h.ORDER_NUMBER as ORDER_NUMBER,
 n.PAYMENT_TERM,
 n.CUSTOMER_NUMBER,
 n.CUSTOMER_NAME,
 h.CUST_PO_NUMBER,
 l.ORDERED_ITEM,
 i.DESCRIPTION,
 l.UNIT_SELLING_PRICE,
 l.TAX_CODE,
 s.TAX_RATE,
 l.SUBINVENTORY,
 h.TRANSACTIONAL_CURR_CODE,
 l.UNIT_SELLING_PRICE * l.SHIPPING_QUANTITY as 未税金额,
 l.UNIT_SELLING_PRICE * (1 + s.TAX_RATE/100) as 含税单价,
 l.UNIT_SELLING_PRICE * l.SHIPPING_QUANTITY * (1 + s.TAX_RATE/100) as 含税金额,
 to_char(l.SCHEDULE_SHIP_DATE, 'yyyymm') as 出货月
FROM
 apps.OE_ORDER_HEADERS_ALL h,
 apps.OE_ORDER_LINES_ALL l,
 apps.YOM_SHIPPING_NOTICE_V n,
 (
 SELECT DISTINCT
  SEGMENT1,
  DESCRIPTION
 FROM
  apps.MTL_SYSTEM_ITEMS
 ) i,
 (
 SELECT
  LINE_ID,
  CASE SUBSTR(TAX_CODE, 8)
   WHEN '免稅' THEN 0
   ELSE to_number(RTRIM(SUBSTR(TAX_CODE, 8) ,'%'))
  END as TAX_RATE
 FROM apps.OE_ORDER_LINES_ALL
 ) s
WHERE
  i.SEGMENT1 = l.ORDERED_ITEM
 AND h.HEADER_ID = l.HEADER_ID
 AND s.LINE_ID = l.LINE_ID
 AND l.LINE_ID = n.ORDER_LINE_ID
 AND REGEXP_LIKE(h.ORDER_NUMBER, '^1[1|3].*')
UNION
SELECT
 NULL,
 to_char(l.SCHEDULE_SHIP_DATE, 'yyyy-mm-dd') as SHIPMENT_DATE,
 NULL,
 l.SHIPPING_QUANTITY,
 l.ORDER_QUANTITY_UOM,
 h.ORDER_NUMBER as ORDER_NUMBER,
 NULL, NULL, NULL,
 h.CUST_PO_NUMBER,
 l.ORDERED_ITEM,
 i.DESCRIPTION,
 l.UNIT_SELLING_PRICE,
 l.TAX_CODE,
 s.TAX_RATE,
 l.SUBINVENTORY,
 h.TRANSACTIONAL_CURR_CODE,
 l.UNIT_SELLING_PRICE * l.SHIPPING_QUANTITY as 未税金额,
 l.UNIT_SELLING_PRICE * (1 + s.TAX_RATE/100) as 含税单价,
 l.UNIT_SELLING_PRICE * l.SHIPPING_QUANTITY * (1 + s.TAX_RATE/100) as 含税金额,
 to_char(l.SCHEDULE_SHIP_DATE, 'yyyymm') as 出货月
FROM
 apps.OE_ORDER_HEADERS_ALL h,
 apps.OE_ORDER_LINES_ALL l,
 (
 SELECT DISTINCT
  SEGMENT1,
  DESCRIPTION
 FROM
  apps.MTL_SYSTEM_ITEMS
 ) i,
 (
 SELECT
  LINE_ID,
  CASE SUBSTR(TAX_CODE, 8)
   WHEN '免稅' THEN 0
   ELSE to_number(RTRIM(SUBSTR(TAX_CODE, 8) ,'%'))
  END as TAX_RATE
 FROM apps.OE_ORDER_LINES_ALL
 ) s
WHERE
  i.SEGMENT1 = l.ORDERED_ITEM
 AND h.HEADER_ID = l.HEADER_ID
 AND s.LINE_ID = l.LINE_ID
 AND REGEXP_LIKE(h.ORDER_NUMBER, '^12.*')
ORDER BY ORDER_NUMBER
