select * from (
SELECT DISTINCT
 CASE  WHEN LINE_TYPE IN('1.0一般銷貨(內銷)','2.0一般銷貨(外銷)','4.0BD規(內銷)') THEN '出货'
				 WHEN LINE_TYPE = 'R1.0一般銷退(內銷)' THEN '销退'
				 WHEN LINE_TYPE = 'R4.1折讓BD規(內銷)' THEN '折让'
				 WHEN LINE_TYPE = 'R1.1折讓(內銷)' THEN '折让'
				 WHEN SUBINVENTORY IN ('S1SCA','S1SCB','F1SCA','F1SCB','FQSCA','FXSCA') THEN '报废品'
         WHEN UNIT_SELLING_PRICE = 0 THEN '送样'
         ELSE '' END AS SaleType,
  (CASE WHEN SUBSTR(ORDERED_ITEM, 0, 1)='F' OR SUBSTR(ORDERED_ITEM, 0, 1)='D' THEN regexp_substr(DESCRIPTION, '[0-9|\.]*"')
   ELSE '' END) AS "Size",
    SHIPMENT_DATE As ShipmentDate,
		TRIP_NO As TripNO,
		SOURCE_ID As SourceID,
		LINE_ID As LineID,
		SHIPPING_QUANTITY AS ShipQuantity,
		DELIVERY_NO As DeliveryNo,
    ROUND(SHIPPING_QUANTITY*(UNIT_LENGTH*UNIT_WIDTH)/1000000) AS ShipAera,
		ORDERED_ITEM AS OrderedItem,
    ROUND(未税金额) AS NonTaxAmount,
		ROUND(含税金额) AS TaxAmount,
		LINE_TYPE,
    ORDER_NUMBER,
    UNIT_SELLING_PRICE AS UnitSellPrice,
    SUBINVENTORY AS Subinventory,
    DESCRIPTION AS Description,
    CUSTOMER_NAME As CustomerName,
  (CASE WHEN regexp_like(ORDERED_ITEM, 'W[a-z|A-Z|0-9]*') THEN '包材'
     WHEN regexp_like(ITEM_CODES, '.*AG.*') THEN 'F'
     ELSE 'R' END) AS "FRUD",
    UNIT_LENGTH*UNIT_WIDTH/1000000 AS UnitAera,
    含税单价 As TaxPrice
FROM
(
    SELECT
        *
    FROM (
 (SELECT
n.TRIP_NO,
l.LINE_ID AS SOURCE_ID,
l.LINE_ID,
to_char( l.ACTUAL_SHIPMENT_DATE, 'yyyy-mm-dd' )  AS SHIPMENT_DATE,
n.DELIVERY_NO,
l.SHIPPING_QUANTITY SHIPPING_QUANTITY,
l.ORDER_QUANTITY_UOM,
l.LINE_TYPE,
h.ORDER_NUMBER AS ORDER_NUMBER,
n.PAYMENT_TERM,
n.CUSTOMER_NUMBER,
n.CUSTOMER_NAME,
h.CUST_PO_NUMBER,
l.ORDERED_ITEM,
i.DESCRIPTION,
(REGEXP_SUBSTR(i.DESCRIPTION, '[a-z|A-Z|0-9]*')) as ITEM_CODES,
l.UNIT_SELLING_PRICE,
l.TAX_CODE,
s.TAX_RATE,
l.SUBINVENTORY,
h.TRANSACTIONAL_CURR_CODE,
l.UNIT_SELLING_PRICE * l.SHIPPING_QUANTITY AS 未税金额,
l.UNIT_SELLING_PRICE * ( 1 + s.TAX_RATE / 100 ) AS 含税单价,
l.UNIT_SELLING_PRICE * l.SHIPPING_QUANTITY * ( 1 + s.TAX_RATE / 100 )  AS 含税金额,
to_char( l.ACTUAL_SHIPMENT_DATE, 'yyyy-mm-dd' ) AS 出货月
FROM
				apps.OE_ORDER_HEADERS_V h,
				apps.OE_ORDER_LINES_V l,
				apps.YOM_SHIPPING_NOTICE_V n,
				( SELECT DISTINCT SEGMENT1, DESCRIPTION FROM apps.MTL_SYSTEM_ITEMS ) i,
				(
				SELECT
				 LINE_ID,
				CASE
					SUBSTR( TAX_CODE, 8 )
					WHEN '免稅' THEN
 					0 ELSE to_number(
					RTRIM( SUBSTR( TAX_CODE, 8 ), '%' ))
				 END AS TAX_RATE
				FROM
				 apps.OE_ORDER_LINES_ALL
				) s
WHERE
i.SEGMENT1 = l.ORDERED_ITEM
AND h.HEADER_ID = l.HEADER_ID
AND s.LINE_ID = l.LINE_ID
AND l.LINE_ID = n.ORDER_LINE_ID
AND REGEXP_LIKE ( h.ORDER_NUMBER, '^1[1|3].*' )
UNION
SELECT
NULL,
s.SOURCE_ID AS SOURCE_ID,
l.LINE_ID,
to_char( l.ORDERED_DATE, 'yyyy-mm-dd' ) AS SHIPMENT_DATE,
NULL,
-l.ORDERED_QUANTITY AS SHIPPING_QUANTITY,
l.ORDER_QUANTITY_UOM,
l.LINE_TYPE,
h.ORDER_NUMBER AS ORDER_NUMBER,
h.TERMS as PAYMENT_TERM,
h.CUSTOMER_NUMBER,
h.SOLD_TO as CUSTOMER_NUMBER,
h.CUST_PO_NUMBER,
l.ORDERED_ITEM,
i.DESCRIPTION,
(REGEXP_SUBSTR(i.DESCRIPTION, '[a-z|A-Z|0-9]*')) as ITEM_CODES,
l.UNIT_SELLING_PRICE,
l.TAX_CODE,
s.TAX_RATE,
l.SUBINVENTORY,
h.TRANSACTIONAL_CURR_CODE,
-l.UNIT_SELLING_PRICE * l.ORDERED_QUANTITY AS 未税金额,
l.UNIT_SELLING_PRICE * ( 1 + s.TAX_RATE / 100 ) AS 含税单价,
 -l.UNIT_SELLING_PRICE * l.ORDERED_QUANTITY * ( 1 + s.TAX_RATE / 100 ) AS 含税金额,
to_char( l.ORDERED_DATE, 'yyyy-mm-dd' ) AS 出货月
FROM
apps.OE_ORDER_HEADERS_V h,
apps.OE_ORDER_LINES_V  l,
( SELECT DISTINCT SEGMENT1, DESCRIPTION FROM apps.MTL_SYSTEM_ITEMS ) i,
(
SELECT
 LINE_ID,
CASE
  WHEN REFERENCE_LINE_ID IS NULL THEN SOURCE_DOCUMENT_LINE_ID
	ELSE REFERENCE_LINE_ID
	END AS SOURCE_ID,
CASE
  SUBSTR( TAX_CODE, 8 )
  WHEN '免稅' THEN
  0 ELSE to_number(
  RTRIM( SUBSTR( TAX_CODE, 8 ), '%' ))
 END AS TAX_RATE
FROM
 apps.OE_ORDER_LINES_ALL
) s
WHERE
i.SEGMENT1 = l.ORDERED_ITEM
AND h.HEADER_ID = l.HEADER_ID
AND s.LINE_ID = l.LINE_ID
AND REGEXP_LIKE ( h.ORDER_NUMBER, '^12.*' )
)
ORDER BY
ORDER_NUMBER

    ) SQL1
    LEFT JOIN (
        SELECT
            DISTINCT A.ITEM_CODE,
            A.ONHAND_QUANTITY,
            B.UNIT_LENGTH,
            B.UNIT_WIDTH,
            B.ATTRIBUTE3,
            SUBSTR(
                SUBSTR(
                    B.DESCRIPTION,0,INSTR(B.DESCRIPTION,'"')
                ),
                INSTR(
                    SUBSTR(
                        B.DESCRIPTION,0,INSTR(B.DESCRIPTION,'"')
                    ),';',-1,1
                )+1
            ) AS SIZE_WITH_QUOTE,
            CASE WHEN B.ATTRIBUTE3='下片' THEN 'R'
                 WHEN B.ATTRIBUTE3='上片' THEN 'F'
                 ELSE '' END AS FRFRFR
        FROM
            APPS.YWMS_ONHAND_QUANTITY A
        INNER
            JOIN APPS.MTL_SYSTEM_ITEMS B
        ON
            A.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID
				AND
					  A.CATEGORY_SEG1 IN('成品', '半成品')
    ) SQL2
    ON
        SQL1.ORDERED_ITEM=SQL2.ITEM_CODE
)
		where SHIPMENT_DATE like '%thisday%'
		ORDER BY SHIPMENT_DATE
)