select F.asset_id 资产编号
			,C.DESCRIPTION 资产名称
			,存放地点
			,SUBSTR(TO_CHAR(F.DEPRN_START_DATE,'YYYY-mm-dd'),0,10) 资本化时间
			,F.LIFE_IN_MONTHS 使用期
			,F.COST 本币原值
			,累计折旧
from
(SELECT A.COST ,
A.asset_id
,A.DEPRN_START_DATE
,A.SALVAGE_VALUE
,A.LIFE_IN_MONTHS
FROM apps.FA_BOOKS A
,(select max(date_effective)AS date_effective,asset_id   from apps.FA_BOOKS WHERE TO_CHAR(date_effective,'YYYY-MM')<='2018-04' group by asset_id ORDER BY asset_id) B
WHERE A.date_effective = B.date_effective
AND A.asset_id =B.asset_id) F

,APPS.FA_ADDITIONS_B B
,APPS.FA_ADDITIONS_TL C
,(SELECT A.ASSET_ID,E.SEGMENT1 ||'.'|| E.SEGMENT2||'.' || E.SEGMENT3 || E.SEGMENT4 存放地点
	FROM apps.FA_BOOKS A
			,(SELECT Z.LOCATION_ID,Z.ASSET_ID
				FROM APPS.FA_DISTRIBUTION_HISTORY Z, (SELECT MAX(DATE_EFFECTIVE) DATE_EFFECTIVE,ASSET_ID FROM APPS.FA_DISTRIBUTION_HISTORY GROUP BY ASSET_ID) X
				WHERE Z.ASSET_ID = X.ASSET_ID AND Z.DATE_EFFECTIVE = X.DATE_EFFECTIVE) D
			,APPS.FA_LOCATIONS E
	WHERE A.ASSET_ID = D.ASSET_ID AND D.LOCATION_ID = E.LOCATION_ID
	GROUP BY A.ASSET_ID,E.SEGMENT1 ||'.'|| E.SEGMENT2||'.' || E.SEGMENT3 || E.SEGMENT4) Z

-- ,(select sum(DEPRN_AMOUNT) 累计折旧,ASSET_ID from APPS.FA_DEPRN_DETAIL where TO_CHAR(DEPRN_RUN_DATE,'YYYY-MM-dd') <= '2018-05'||'-10' GROUP BY ASSET_ID) S
,(select (case when ZZ.ASSET_ID = '10040' then SUM(ZZ.DEPRN_AMOUNT)+7500.68 else SUM(ZZ.DEPRN_AMOUNT) end) 累计折旧,ZZ.ASSET_ID from APPS.FA_DEPRN_DETAIL ZZ where TO_CHAR(ZZ.DEPRN_RUN_DATE,'YYYY-MM') <='2018-05' and ZZ.DEPRN_RUN_DATE <> (select MAX(DEPRN_RUN_DATE) from APPS.FA_DEPRN_DETAIL QQ WHERE ZZ.ASSET_ID = QQ.ASSET_ID AND TO_CHAR(QQ.DEPRN_RUN_DATE,'YYYY-MM') <='2018-05'  GROUP BY QQ.ASSET_ID) GROUP BY ZZ.ASSET_ID) S

WHERE S.ASSET_ID = F.ASSET_ID
	AND	B.ASSET_ID = F.ASSET_ID
	AND F.ASSET_ID = C.ASSET_ID
	AND F.asset_id = Z.asset_id
	AND F.COST <> 0
	AND B.ATTRIBUTE_CATEGORY_CODE NOT LIKE '土地%'
	AND B.ATTRIBUTE_CATEGORY_CODE NOT LIKE '遞延%'
	AND B.ATTRIBUTE_CATEGORY_CODE NOT LIKE '%列管%'
GROUP BY F.asset_id,F.COST,C.DESCRIPTION,存放地点,F.DEPRN_START_DATE,F.LIFE_IN_MONTHS,累计折旧
ORDER BY F.asset_id