SELECT
 REGEXP_SUBSTR(bom.DESCRIPTION, '^[a-z|A-Z|0-9]*[(|;]??') as 产品代码,
 msi.SEGMENT1 as 物料编码,
 '元/' || msi.PRIMARY_UOM_CODE as UOM,
 cry.CURRENCY_CODE as 币别,
 msi.MSIZE,
 FROZEN_COST,
 CURRENT_COST,
 COMPONENT_QUANTITY
FROM
 (
 SELECT DISTINCT
  INVENTORY_ITEM_ID,
  SEGMENT1,
  DESCRIPTION,
  PRIMARY_UOM_CODE,
  (
  CASE PRIMARY_UOM_CODE
   WHEN 'M' THEN RTRIM(REGEXP_SUBSTR(DESCRIPTION, '[0-9|\\.]+mm'), 'mm')
   ELSE PRIMARY_UOM_CODE
  END
  ) as MSIZE
 FROM
  apps.mtl_system_items
 ) msi,
 apps.BOM_BILL_OF_MATERIALS_V bom,
 (
 SELECT
  COMPONENT_ITEM_ID,
  BILL_SEQUENCE_ID,
  COMPONENT_QUANTITY
 FROM
   apps.BOM_INVENTORY_COMPONENTS_V
 ) bc,
 (SELECT INVENTORY_ITEM_ID, ITEM_COST as FROZEN_COST FROM apps.CST_ITEM_COST_TYPE_V WHERE COST_TYPE = 'ZBK-Frozen') fc,
 (SELECT INVENTORY_ITEM_ID, ITEM_COST as CURRENT_COST FROM  apps.CST_ITEM_COST_TYPE_V WHERE COST_TYPE = 'Current') cc,
 (
 SELECT DISTINCT
  A.ITEM_NUMBER,
  C.CURRENCY_CODE
 FROM
  apps.CST_ITEM_COST_TYPE_V A,
  APPS.PO_LINES_ALL B,
  APPS.PO_HEADERS_ALL C
 WHERE
  A.INVENTORY_ITEM_ID = B.ITEM_ID
  AND B.PO_HEADER_ID = C.PO_HEADER_ID
 ) cry
WHERE
 fc.INVENTORY_ITEM_ID = msi.INVENTORY_ITEM_ID
 AND cc.INVENTORY_ITEM_ID = msi.INVENTORY_ITEM_ID
 AND msi.INVENTORY_ITEM_ID = bc.COMPONENT_ITEM_ID
 AND bom.BILL_SEQUENCE_ID = bc.BILL_SEQUENCE_ID
 AND SEGMENT1 = cry.ITEM_NUMBER