SELECT DISTINCT A.ITEM_CODE, B.UNIT_LENGTH/1000 长, B.UNIT_WIDTH/1000 宽，B.UNIT_LENGTH*B.UNIT_WIDTH/1000000 面积
FROM APPS.YWMS_ONHAND_QUANTITY A
 INNER JOIN APPS.MTL_SYSTEM_ITEMS B
 ON A.INVENTORY_ITEM_ID = B.INVENTORY_ITEM_ID
 WHERE A.CATEGORY_SEG1 = '成品'
 AND A.SUBINVENTORY_CODE = 'F1FGA'